export const SAY_HI = "SAY_HI"
export const CREATE_USER = "CREATE_USER"
export const FIND_USER = "FIND_USER"
export const GET_USER = "GET_USER"
export const LOGOUT = "LOGOUT"
export const GET_CONTACTS = "GET_CONTACTS"
export const GET_CONVERSATIONS = "GET_CONVERSATIONS"
export const SET_CURRENT_CONVO = "SET_CURRENT_CONVO"
