export const SAY_HI = "SAY_HI"
export const CREATE_USER = "CREATE_USER"
export const FIND_USER = "FIND_USER"
export const GET_USER = "GET_USER"
export const LOGOUT = "LOGOUT"
export const GET_CONTACTS = "GET_CONTACTS"
